---
- name: Configure Keycloak with Gitea
  gather_facts: no
  hosts: localhost
  vars:
    admin_user: gitea-admin
    admin_password: openshift
    sub_domain: apps.cluster-2trjj.dynamic.redhatworkshops.io
    users: 5
  tasks:

    - name: Generate token and secret
      include_role:
        name: create-token
      vars:
        user: "user{{ item }}"
        user_password: "{{ password }}"
      with_sequence: 1-{{ users }}
