- name: Gitea API call
  debug:
    msg: "Making API call to https://gitea-gitea.{{ sub_domain }}/api/v1/users/{{ user }}/tokens"

- name: Get token
  uri:
    url: https://gitea-gitea.{{ sub_domain }}/api/v1/users/{{ user }}/tokens
    method: POST
    force_basic_auth: true
    user: "{{ user }}"
    password: "{{ user_password }}"
    body_format: json
    status_code: 201
    body:
      # Use random token generator since gitea doesn't like multiple tokens with same name
      name: "{{ 99999999 | random | to_uuid }}"
  register: token_response

- name: extract token
  set_fact:
    token: "{{ token_response.json.sha1 }}"

- name: create secret
  k8s:
    state: present
    definition:
      apiVersion: v1
      kind: Secret
      metadata:
        name: gitea-token
        namespace: "{{ user }}-cicd"
        annotations:
          tekton.dev/docker-0: https://gitea-gitea.{{ sub_domain }}
      type: kubernetes.io/basic-auth
      stringData:
        username: "{{ user }}"
        password: "{{ token }}"
